travis:
  secure:
    BINSTAR_TOKEN: UzDlpyKKwj6SYM6uks7/Pp/rlTYlfuyhi/+ew+kaXEQ1U3EoctV+gLfngBUiiiiUHyEU8xOOMwhe2HS2DzPw8cPenwEpAoB+aamubOKcISIqk1dmMClCZLb+aqkg/G75YzxbtQjtOkiGOeQxCFFTB8xcJTb64KtXy5QN5RRmCg9IRH7FqnBf1itV55JrRymPOr5mHRFG3+7hnDs3Xmd6kYU9KMSgyHqRokoo3GYegjjzAvqrwXkOiaix/TQpKfPko+ysibrz07luxoFWKBnbZ1OWJ4VBZCfzRs7kAeklqgMU/sZd2eOv6kps2+nBJuWN3YKgg23Kw4Vvuf4JQWFdWWSIbg1jrymWekLqGi1HWjZx2aFU9bdq5rBHdLDM9qw8497loBfTAjczEYa60ZiglQUc7+Nqf5qhXIuu+0da5qdx1v1GQkJXYg5Nk8dBZPiKL4UWrZjpWXM82w/C4Z8FHksIUPcdLx4outxhVbGY1UnmU2xQkU4g8EbImsKNheOgkj4vq6/++OYo4Rf5/aUwSF7CCvUDnSsxqoC/pvuSyBI4D83jLUIPGLILFjrClwsvp/cCYmIQ7qXs/liPEQgDYiL17pZylLm3yYncnoDkgbmSCDMLBJmOrQl0BVsVENdTqNawi8d7oS33ZgFVQblEsSToux3lSCQV9Osqmx6JW4o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
